[package]
name = "erebus-server-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
erebus-core = { workspace = true, features = ["server"] }
clap = { version = "4.5.50", features = ["derive"] }
comfy-table = "7.2.1"
tracing-subscriber = "0.3.20"
tracing = "0.1.41"